#!/bin/bash

. "$(dirname $0)/config"

shard_start=1
prefix=testonly

echo "running sigsum-log-go with vk: $log_vk"
$GOPATH/bin/sigsum_log_go \
	--logtostderr --v 3\
	--prefix $prefix \
	--key $log_sk \
	--trillian_id $tree_id \
	--witnesses $wit_vk \
	--shard_interval_start $shard_start
